# Rscript to generate mock microbiomes based on the GROND refseq207full database
# and the King et al. (2019) proposed standard human healthy gut microbiome (referred
# to here as KBGF (Knowledge Base Gut Feeling) or, more commonly, as KB.
# 
# This code is based on  make_mock_v03.R  of 30 October 2025.
# It has 2 Parts, the first of which creates the single large fastq file that is 
# a dataset for the mock mocrobiome of interest, while the second part carries
# out denoising of this dataset.
#
# source("/vast/projects/rrn/ASVset/make_mock_and_denoise.R") 
#
# 9 April 2026                                                                    [cjw]
cat("\n COMMENCING CODE make_mock_and_denoise.R  \n\n")
args = commandArgs(trailingOnly=TRUE)
#######################################################################################
##########################                               ##############################
##########################         INITIALISATIONS       ##############################
##########################                               ##############################
#######################################################################################
if (length(args>0)){
  basepath = args[1]
  whichMock = args[2]
  whichSubunit = args[3]
  whichCase = args[4]
  whichSubMock = args[5]
  whichPair = args[6]
  uppErrRate = args[7]
  maxopnum = as.numeric(args[8])
  nmock = as.numeric(args[9])
  numcores = as.numeric(args[10])
} else {
  basepath = "/vast/projects/rrn/ASVtest"
  whichMock = "mockKB"        # "mSerF"   # "mSerS3"   #    "mSriSZ2"                  
  whichSubunit = "rrn"
  whichCase = "11"
  whichSubMock = 0
  whichPair = 0
  uppErrRate = 0.0100
  maxopnum = 291  # 261 for mock50, 48 for mock10   
  nmock = 59      #  50 for mock50, 10 for mock10
  numcores = 4
}

if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager")
packages <- c("ShortRead", "parallel","tictoc","readxl")   
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  BiocManager::install(packages[!installed_packages])
}
# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

doPART1 = TRUE
#######################################################################################
##########################                               ##############################
##########################           FUNCTIONS           ##############################
##########################                               ##############################
#######################################################################################
generate_RA = function(nmock,M){
  # Generate relative abundances forming a geometric series of nmock elements ranging from
  # 1 to M.
  # 29 July 2025                                                                  [cjw]
  r = exp(log(M)/(nmock-1)) - 1
  RA = sapply(1:nmock,function(j){out=M/((1+r)^(j-1))})
  print(RA)
  RA = RA/sum(RA)
  out = RA
}

extractFastqHeaders=function(basepath,whichSubunit,maxopnum){
  # The fastq files generated by badread are single multisequence files for each operon
  # of all organisms of the mock microbiome.  These are in directory  fastqPath.
  # For each operon the headers of all sequences in that operon's fastq file are needed
  # for initial filtering prior to selecting reads for the mock microbiome of interest.
  # This function returns those header files in directory  file.path(outPath,"text").
  # maxopnum  is the total number of operons.
  # 28 October 2025                                                              [cjw]
  fastqPath = file.path(basepath,"fastq/store",whichSubunit)
  for (opnum in 1:maxopnum){
    pat = paste("Op_",opnum,".fastq",sep="",collapse="")
    F0 = readFastq(dirPath = fastqPath, pattern=pat)
    argstrh1=paste(" '^@'  ",basepath,"/fastq/store/",whichSubunit,"/reads_",whichSubunit,"_Op_",opnum,
                    ".fastq > ",basepath,"/text/temp_",opnum,"_headers.txt",sep="")
    system2("grep", args=argstrh1)
    argstrh2=paste(" 'strand'  ",basepath,"/text/temp_",opnum,"_headers.txt > ",basepath,
                     "/text/reads_",whichSubunit,"_Op_",opnum,"_headers.txt",sep="")
    system2("grep", args=argstrh2)
  }
  system2("rm",args= paste(basepath,"/text/temp*headers.txt",sep=""))
}


BRfastq_filtPID = function(i, basepath, whichSubunit, minReadLength=4200, makeplot1=TRUE){ 
  opnum=i  
  stem = paste("reads_",whichSubunit,"_Op_",opnum,sep="")           #  unlist(strsplit(fastqName,split="[.]"))[1]
  readHeadersName = paste("reads_",whichSubunit,"_Op_",opnum,"_headers.txt",sep="")
  X = readLines(con=file.path(basepath,"text",readHeadersName))
  igood = which(sapply(1:length(X), function(j){nchar(X[j])< 180}))  
  newname = paste(stem,"_Qstripped.txt",sep="")
  writeLines(X[igood],con=file.path(basepath,"text",newname))
  T = read.delim(file=file.path(basepath,"text",newname),sep=" ")
  nr = nrow(T)
  colnames(T) = c("ID.ont","ID.mock","ReadLength","FragLength","ReadPID")
  #  print(T[1,])
  
  # Now parse ID.mock, ReadLength, FragLength, ReadPID to extract the key data.
  splitChar = c("",",","=","=","=")
  cname = c("ID.ont","ID.mock","ReadLength","FragLength","ReadPID")
  IDvec = rep("",nr);   Strand=rep(-9,nr)  
  ReadLen = rep(0,nr);  FragLen = rep(0,nr);   PID = rep(0.0,nr)
  for (jr in 1:nr){
    for (jc in 2:5){
      t1 = unlist(strsplit(T[jr,cname[jc]],split=splitChar[jc]))
      if (length(t1)>1){
        if (jc==2){
          cstrand = substr(t1[2],start=1,stop=1)
          Strand[jr] = ifelse(cstrand=="+",1,-1)
        } else {
          t11 = t1[2]
          if (jc==3){
            ReadLen[jr] = as.integer(t11)
          } else if (jc==4){
            FragLen[jr] = as.integer(t11)
          } else {
            PID[jr] = as.numeric(as.numeric(substr(t11,start=1,stop=nchar(t11)-1)))
          }
        }
      } else {
        cat("Improper split character for operon",opnum," row",jr, " column",jc,"\n")
        cat("   T[jr,cname[jc]]:  ",T[jr,cname[jc]]," split character:  ",splitChar[jc],"\n")
      }
    }
  }
  T.df = data.frame(ID=T[1:nr,1], strand=Strand, readLength=ReadLen, fragLength=FragLen,PID=PID)
  ifilt1 = which(sapply(1:length(T.df$PID),function(j){T.df$PID[j]>98.75 && T.df$readLength[j]>minReadLength}))  
  cat("Number of retained reads after initial filtering (PID=98.75) is ",length(ifilt1),"\n")
  if (makeplot1){
    plotname1 = paste(stem,"_histos_PID_Qmean_Op_",opnum,".pdf",sep="")
    pdf(file=file.path(basepath,"plots",plotname1),paper="a4")
    par(mfrow=c(2,2))
    hist(T.df[,"PID"],xlab="PID",main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" ") )
    hist(log10(100.001-T.df[,"PID"]),xlab="log10(100.001 - PID)",
         main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" ")) #   which(T.df$PID<98.75)
    breaks1 = 100 - seq(98.74,100,by = 0.02)
    hist(1-T.df[ifilt1,"PID"]/100,breaks=breaks1/100,
         xlab="Fraction Identical",main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" "))
    hist(log10(1.00001-T.df[ifilt1,"PID"]/100),
         xlab="log10(1.00001 - PID/100) (= log10(mismatch rate))",main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" "))
    dev.off()
  }
  outname1 = paste(stem,"_metadata_Pidfilt_Op_",opnum,".RData",sep="")
  save(T.df,ifilt1,file=file.path(basepath,"RData",outname1))
  out = list(Tdf = T.df, PIDfilt=ifilt1)
}


which_specR = function(specName){
  out=which(sapply(1:length(specR),function(j){specR[[j]]$species.ordered==specName}))
}

linKBtospecR = function(inname){
  # Creates key objects and mappings for 
  #    1. Identifying which KB strains have entries in specR;
  #    2. Ordering KB strains by relative abundance;
  #    3. Mapping abundance-ordered KB strains to their corresponding specR entries.
  #    4. Determining strain operons for any KB strain in specR.
  # 11 August 2025 
  # Load crapOpNames, opDB.species, opDB.strains, OpNames, ops_per_strain_each_spec, specR
  # inname = "specR_etal_grondDB.RData"
  load(file.path(basepath,"RData",inname))
  
  constructing=FALSE
  if (constructing){
    # Load King's Gut Feeling Knowledge Base.
    gfkb.name = "KGFDB.xlsx"  #  "King CH etal SuppMat S4 Table GutFeeling.KB PLoSOne.0206484.s008.xlsx"
    KB = read_excel(file.path(basepath,"GROND",gfkb.name))
    # Build the mapping from KB to specR
    KBspecR = matrix(0,nrow=164,ncol=3)
    colnames(KBspecR) = c("ind.specR","opLow","opHi")
    # Manually repeat the following for j =1:164, saving the work after each value of j.
    outnameK = "KBspecR_matrix.RData"
    # load(file.path(grondPath,"output/RData",outnameK))
    j=22
    print(KB[j,c(3,8)])
    iz = which_specR("Escherichia coli")
    print(specR[[iz]]$strainOps)
    # KBspecR[j,] = c(0,-1,-1)
    KBspecR[j,] = c(iz,1,2)
    save(KBspecR,file=file.path(basepath,"RData",outnameK))
  }     #     end     conditional   constructing    block
  
  innameK = "KBspecR_matrix.RData"
  load(file.path(basepath,"RData",innameK))
  kbgood = which(KBspecR[,"opHi"]>0);  nkbgd = length(kbgood)
  # for (j in 1:nkbgd){print(specR[[KBspecR[kbgood[j],1]]]$strainOps[KBspecR[kbgood[j],2]:KBspecR[kbgood[j],3]])}
  
  # Get KB and KB abundance data to guide rank-ordering on KB abundance data of the strains being used 
  # in mock microbiomes.
  gfkb.name = "KGFDB.xlsx"  #  "King CH etal SuppMat S4 Table GutFeeling.KB PLoSOne.0206484.s008.xlsx"
  KB = read_excel(file.path(basepath,"GROND",gfkb.name))
  
  abundKB.name = "KGFDB_Abundance_Tables.xlsx"
  AbundKB = read_excel(file.path(basepath,"GROND",abundKB.name))
  ord.abKB = order(AbundKB$Average,decreasing=TRUE)
  # Relation between KB and AbundKB is derived with the following:-
  # Define jord.abund as an index on kbgood such that KB[kbgood[jord.abund]],] gives
  # the KB rows that have strains ordered in descending relative abundances. 
  
  jord.abund = matrix(0,nrow=59,ncol=2)
  jord.abund[1,] = c(33,2);    jord.abund[2,] = c(14,8);    jord.abund[3,] = c(34,13)
  jord.abund[4,] = c(22,14);   jord.abund[5,] = c(52,20);   jord.abund[6,] = c(58,21)
  jord.abund[7,] = c(65,24);   jord.abund[8,] = c(24,26);   jord.abund[9,] = c(54,33)
  jord.abund[10,] = c(71,42);  jord.abund[11,] = c(9,44);  jord.abund[12,] = c(28,48)
  jord.abund[13,] = c(85,49);  jord.abund[14,] = c(67,59);  jord.abund[15,] = c(35,60)
  jord.abund[16,] = c(66,61);  jord.abund[17,] = c(25,62);  jord.abund[18,] = c(57,63)
  jord.abund[19,] = c(11,64);  jord.abund[20,] = c(47,65);  jord.abund[21,] = c(73,67)
  jord.abund[22,] = c(60,68);  jord.abund[23,] = c(55,70);  jord.abund[24,] = c(88,72)
  jord.abund[25,] = c(30,73);  jord.abund[26,] = c(59,74);  jord.abund[27,] = c(36,75)
  jord.abund[28,] = c(72,78);  jord.abund[29,] = c(26,79);  jord.abund[30,] = c(10,80)
  jord.abund[31,] = c(18,81);  jord.abund[32,] = c(39,84);  jord.abund[33,] = c(37,85)   
  jord.abund[34,] = c(50,95);  jord.abund[35,] = c(62,98);  jord.abund[36,] = c(79,99)
  jord.abund[37,] = c(46,100); jord.abund[38,] = c(68,106); jord.abund[39,] = c(86,108)
  jord.abund[40,] = c(45,110); jord.abund[41,] = c(61,111); jord.abund[42,] = c(16,113)
  jord.abund[43,] = c(75,115); jord.abund[44,] = c(27,116); jord.abund[45,] = c(31,119)
  jord.abund[46,] = c(64,120); jord.abund[47,] = c(32,121); jord.abund[48,] = c(80,125)
  jord.abund[49,] = c(17,128); jord.abund[50,] = c(51,129); jord.abund[51,] = c(29,130)    
  jord.abund[52,] = c(56,135); jord.abund[53,] = c(84,137); jord.abund[54,] = c(70,139)
  jord.abund[55,] = c(77,144); jord.abund[56,] = c(83,148); jord.abund[57,] = c(89,149)
  jord.abund[58,] = c(63,150); jord.abund[59,] = c(23,155)
  
  
  ## For the kth most abundant strain in KB that has strain data in specR here are the
  ## strain operon names:-
  #k = 5;    specRinds3 =  KBspecR[kbgood[jord.abund[k,1]],]
  #specR[[specRinds3[1]]]$strainOps[specRinds3[2]:specRinds3[3]]
  ## and here is the full specR detail:-
  #print(specR[[specRinds3[1]]])
  ra1 = AbundKB[ord.abKB[jord.abund[,2]],16]$Average
  RAkbg = ra1/sum(ra1)
  
  #print(cbind(KB[kbgood[jord.abund[,1]],8], AbundKB[ord.abKB[jord.abund[,2]],c(3,16)]))
  out = list(kbgood,ord.abKB,jord.abund,KB,specR,KBspecR,RAkbg)
}
######################################################################################
############################     RUN INITIALISATION      ##############################
#######################################################################################
subSampleFactor = 1
fastqPath = file.path(basepath,"fastq")
makeplot1 = FALSE  # Covering plotting in PID filtering function
#recipER = round(1/uppErrRate) 

if (whichMock %in% c("mSriSA1","mSriSA2","mSriSA3","mSriSA4","mSriSZ1","mSriSZ2","mSriSZ3","mSriSZ4")){
  whichPair = substr(whichMock, start=7,stop=7)
  if (!(whichSubunit == "rrn")){
    cat("Incompatibility of mock microbiome with whichSubunit.  Selecting rrn \n")
    whichSubunit = "rrn"
  }
  maxopnum = -1 
  nmock = -1  
}
if (whichMock %in% c("mSerS1","mSerS2","mSerS3","mSerS4")){
  whichSubMock = substr(whichMock, start=6,stop=6)
  if (!(whichSubunit %in% c("16S","23S"))){
    cat("Incompatibility of mock microbiome with whichSubunit.  Selecting 16S \n")
    whichSubunit = "16S"
  }
  maxopnum = -1 
  nmock = -1  
}

if (whichMock=="mockKB"){
  mstr = whichMock 
  dataset = paste("mKB",whichSubunit,paste("C",whichCase,sep=""),sep="_")
  stem1 = paste(mstr,whichSubunit,"Case",whichCase,sep="_")
} else if (whichMock=="mSerF"){
  mstr="mSerF"
  dataset = paste(whichMock,whichSubunit,paste("C",whichCase,sep=""),sep="_")
  stem1 = paste(whichMock,whichSubunit,"Case",whichCase,sep="_")
} else if ("mSerS" == substr(whichMock,1,5)){
  mstr="mSerS"
  dataset = paste(whichMock,whichSubunit,paste("C",whichCase,sep=""),sep="_")
  stem1 = paste(whichMock,whichSubunit,"Case",whichCase,sep="_")
} else if (substr(whichMock,1,6) == "mSriSA"){
  mstr="SA"
  dataset = paste(paste(mstr,whichPair,sep=""),whichSubunit,paste("C",whichCase,sep=""),sep="_")
  stem1 = paste(paste(mstr,whichPair,sep=""),whichSubunit,"Case",whichCase,sep="_")
} else if (substr(whichMock,1,6) == "mSriSZ"){
  mstr="SZ"
  dataset = paste(paste(mstr,whichPair,sep=""),whichSubunit,paste("C",whichCase,sep=""),sep="_")
  stem1 = paste(paste(mstr,whichPair,sep=""),whichSubunit,"Case",whichCase,sep="_")
} else {
  mstr ="invalid"
}

minReadLength = ifelse(whichSubunit=="rrn",4200, ifelse(whichSubunit=="23S",1800, 1100))
# minReadLength is used as a second filter in  BRfastq_filtPID()  function
if (nchar(whichMock)>3){
  doPART1 = substr(whichMock,start=1,stop=4) == "mock"
} else doPART1 = FALSE

#######################################################################################
#######################################################################################
##########################                               ##############################
##########################           MAIN BODY           ##############################
##########################                               ##############################
#######################################################################################
#######################################################################################
cat("\n COMMENCING CODE make_mock_and_denoise.R  \n\n")
if (doPART1){
  # PART 1:  For simulated reads mock microbiomes, construct the read library of rRNA
  #          16S rRNA gene, or 23S rRNA gene or rrn operon reads in the form of a single
  #          fastq file.
  #          N.B.: Can only be run after generation of simulated reads has completed, as 
  #                this gives us the fastq records for each read of each operon.
  
  DKB = linKBtospecR("specR_etal_grondDB.RData")
  kbgood = DKB[[1]];              nkbgd = length(kbgood) 
  jord.abund = DKB[[3]];          njab = nrow(jord.abund)
  KBspecR = DKB[[6]]
  RAkbg = DKB[[7]]
  indlow.strainOps = KBspecR[kbgood[jord.abund[,1]],"opLow"]
  indupp.strainOps = KBspecR[kbgood[jord.abund[,1]],"opHi"]
  num_ops_per_species = sapply(1:length(indupp.strainOps),function(j){indupp.strainOps[j] - indlow.strainOps[j]+1})
  
  
  # It is possible to filter on strandedness, so this will be implemented as an option.
  # Implement quality filtering using the header information on read PID values.
  extractFastqHeaders(basepath,whichSubunit,maxopnum)
  
  # Now filter the reads. This call generates a metadata file for each operon holding:-
  #    T.df    A data.frame(ID=T[1:nr,1], strand=Strand, readLength=ReadLen, fragLength=FragLen,PID=PID)
  #    ifilt1  A vector of indices into T.df that identifies reads with PID > 98.75 
  #        where T[j,1] is the strain-informative part of the jth fastq sequence's name.
  # BRfastq_filtPID = function(i,basepath,whichSubunit,makeplot1=TRUE)
  strainName = rep("",maxopnum)
  PIDFilts = vector("list",maxopnum)
  for (i in 1:maxopnum){
    PIDFilts[[i]] = BRfastq_filtPID(i,basepath, whichSubunit, minReadLength, makeplot1=FALSE)
    strainName[i] = PIDFilts[[i]][[1]][1,1]
    cat("Opnum ",i,"   strainName ",strainName[i], "  length(ifilt1) ",length(PIDFilts[[i]][[2]]),"\n")
  }
  
  PIDFilts = mclapply(1:maxopnum,BRfastq_filtPID,basepath,whichSubunit,minReadLength,makeplot1=FALSE,,mc.cores=numcores)
  cat("Completed filtering calculation. \n")
  
  # Determine the maximum number of sequences for the most abundant species.  This requires
  # determination of the minimum number of simulated sequences for the various operons of 
  # this species.
  minFastqSeq = 10000000
  iPIDfilt = vector("list",length(num_ops_per_species[1]))
  for (jop in 1:num_ops_per_species[1]){
    inname = paste("reads_",whichSubunit,"_Op_",jop,"_metadata_Pidfilt_Op_",jop,".RData",sep="")
    load(file.path(basepath,"RData",inname))
    iPIDfilt[[jop]] = ifilt1
    ipostr= which(T.df$strand[ifilt1]>0);  inegstr = which(T.df$strand[ifilt1]<0)
    minFastqSeq = min(minFastqSeq,length(ipostr))
    print(c(length(ipostr),minFastqSeq))
  }
  
  if (whichMock=="mock50"){
    # Select a value of M to define the range of relative abundances from 1 to M - e.g. M=1000
    M = 1000
    RA = generate_RA(nmock,M)
  } else if (whichMock%in% c("mockKB","mockKQ")){
    RA = RAkbg
  } else { # The mock10 case
    # From King etal's GFDB the relative abundances for the selected species are
    abund.Z = c(0.15, 0.0378, 0.0218, 0.0112, 0.00491,0.00259, 0.00185, 0.000705, 0.000046, 0.000042)
    RA = abund.Z/sum(abund.Z)
  }
  indOp = matrix(c(c(1,1+cumsum(num_ops_per_species[1:(nmock-1)])),cumsum(num_ops_per_species)),nrow=nmock,ncol=2)
  totReads = round(subSampleFactor*minFastqSeq/RA[1]  - 1)
  numReads_per_operon_of_species = (totReads*RA)%/%1
  Ntotreads = sum(sapply(1:nmock,function(j){numReads_per_operon_of_species[j]*num_ops_per_species[j]}))
  cat("Number of reads per operon of each strain is \n",numReads_per_operon_of_species,"\n")
  cat("Number of reads in this dataset is ",Ntotreads,"\n")
  
  
  # Select the fastq records that are to be retained for each operon, and write to file.
  qmode="w"
  mockFastqName = paste(stem1,".fastq",sep="")
  x1 = list.files(path=file.path(basepath,"fastq"),pattern=mockFastqName)
  if (length(x1)>0){
    argstr = paste(" ",file.path(basepath,"fastq",mockFastqName,sep=""))
    system2(rm, args=argstr1)
  }
  cat("\n Commencing writing of fastq records for all reads to file ",mockFastqName,"\n")
  for (jsp in 1:nmock){
    nR = numReads_per_operon_of_species[jsp]
    for (jop in indOp[jsp,1]:indOp[jsp,2]){
      inname = paste("reads_",whichSubunit,"_Op_",jop,"_metadata_Pidfilt_Op_",jop,".RData",sep="")
      load(file.path(basepath,"RData",inname))
      ipostr= which(T.df$strand[ifilt1]>0);  inegstr = which(T.df$strand[ifilt1]<0)
      cat("jsp jop length(ipostr) length(inegstr),nR: ",jsp, jop, length(ipostr), length(inegstr),nR,"\n")
      isamp = sample(1:length(ipostr),nR)
      iPIDfilt[[jop]] = ifilt1
      fastqname = paste(stem1,jop,".fastq",sep="")
      pat = paste("Op_",jop,".fastq",sep="")
      F = readFastq(dirPath = file.path(basepath,"fastq/store",whichSubunit), pattern=pat)
      writeFastq(F[ifilt1[ipostr[isamp]]],file.path(basepath,"fastq",mockFastqName),mode=qmode, compress=FALSE)
      qmode = "a"
    }
  }

  cat("Completed PART 1")
} else {
  cat("\n PART 1 not executed because the microbiome is not one with simulated reads. \n")
}

# PART 2: Create sbatch call for RAD denoising. Then dispatch that call via system2().
setwd(basepath)  
argstr1 = paste(" --mem=24GB --time=48:00:00 juliaRADrun.sh ",basepath,whichMock,
                         whichSubunit, whichCase, whichSubMock,whichPair, uppErrRate,sep=" ",collapse=" ")
cat("\n\n sbatch call argstr ",argstr1,"\n\n)")
system2("sbatch",args=argstr1)






