# Rscript to generate mock microbiomes from the store of operon fastq sequences
# for the selected mock microbiome.  The store of operons was generated from code 
# make_mock_store.R.
# 
#
# source("/vast/projects/rrn/nanoporeSimulation/make_mock_variants.R") 
#
# 11 August 2025                                                                    [cjw]
args = commandArgs(trailingOnly=TRUE)
#######################################################################################
##########################                               ##############################
##########################         INITIALISATIONS       ##############################
##########################                               ##############################
#######################################################################################
slurm = TRUE
if (length(args>0)){
  maxopnum = args[1]
  numcores = args[2]
} else {
  maxopnum = 261   # 261 for mock50, 48 for mock10     
  numcores = 2
}

if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager")
packages <- c("ShortRead", "parallel","tictoc","readxl")    # Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  BiocManager::install(packages[!installed_packages])
  #  BiocManager::install(packages[!installed_packages],repos="https://cran.ms.unimelb.edu.au/")
}# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

basepath = "/vast/projects/rrn/nanoporeSimulation"


#######################################################################################
##########################                               ##############################
##########################           FUNCTIONS           ##############################
##########################                               ##############################
#######################################################################################
generate_RA = function(nmock,M){
  # Generate relative abundances forming a geometric series of nmock elements ranging from
  # 1 to M.
  # 29 July 2025                                                                  [cjw]
  r = exp(log(M)/(nmock-1)) - 1
  RA = sapply(1:nmock,function(j){out=M/((1+r)^(j-1))})
  print(RA)
  RA = RA/sum(RA)
  out = RA
}

extractFastqHeaders=function(fastqPath,outPath,maxopnum){
  # The fastq files generated by badread are single multisequence files for each operon
  # of all organisms of the mock microbiome.  These are in directory  fastqPath.
  # For each operon the headers of all sequences in that operon's fastq file are needed
  # for initial filtering prior to selecting reads for the mock microbiome of interest.
  # This function returns those header files in directory  file.path(outPath,"text").
  # maxopnum  is the total number of operons.
  # 30 July 2025                                                              [cjw]
  for (opnum in 1:maxopnum){
    pat = paste("Op_",opnum,".fastq",sep="",collapse="")
    F0 = readFastq(dirPath = fastqPath, pattern=pat)
    argstrh1=paste(" '^@'  ",outPath,"/fastq/",whichSubunit,"/reads_",whichSubunit,"_Op_",opnum,".fastq > ",outPath,"/text/temp_",opnum,"_headers.txt",sep="")
    system2("grep", args=argstrh1)
    argstrh2=paste(" 'strand'  ",outPath,"/text/temp_",opnum,"_headers.txt > ",outPath,"/text/reads_",whichSubunit,"_Op_",opnum,"_headers.txt",sep="")
    system2("grep", args=argstrh2)
  }
  system2("rm",args= paste(outPath,"/text/temp*headers.txt",sep=""))
}


readQscore = function(i,frags.Q,start_trim){
  t1 = as.character(frags.Q[[i]])
  t1c = unlist(strsplit(t1,split=""))
  t1.Q = sapply(1:nchar(t1),function(j){as.integer(charToRaw(t1c[j]))-33})
  t1.Qmean = -10*log10(mean(sapply(start_trim:nchar(t1),function(j){10^(-t1.Q[j]/10)})))
  t1.Qstd = -10*log10(sd(sapply(start_trim:nchar(t1),function(j){10^(-t1.Q[j]/10)})))
  t1.meanQ = mean(t1.Q)
  out = t1.Qmean       #  c(t1.Qmean,t1.Qstd,t1.meanQ)
}

# mclapply(1:maxopnum,BRfastq_filtPID,fastqPath,whichSubunit,BRoutput,makeplot1,mc.cores=numcores)
BRfastq_filtPID = function(i,fastqPath,whichSubunit,BRoutput,makeplot1=TRUE){ 
  opnum=i  
  stem = paste("reads_",whichSubunit,"_Op_",opnum,sep="")           #  unlist(strsplit(fastqName,split="[.]"))[1]
  readHeadersName = paste("reads_",whichSubunit,"_Op_",opnum,"_headers.txt",sep="")
  inpath = file.path(fastqPath,readHeadersName)
  X = readLines(con=file.path(basepath,BRoutput,"text",readHeadersName))
  igood = which(sapply(1:length(X), function(j){nchar(X[j])< 180}))  
  newname = paste(stem,"_Qstripped.txt",sep="")
  writeLines(X[igood],con=file.path(basepath,BRoutput,"text",newname))
  T = read.delim(file=file.path(basepath,BRoutput,"text",newname),sep=" ")
  nr = nrow(T)
  colnames(T) = c("ID.ont","ID.mock","ReadLength","FragLength","ReadPID")
  print(T[1,])
  
  # Now parse ID.mock, ReadLength, FragLength, ReadPID to extract the key data.
  splitChar = c("",",","=","=","=")
  cname = c("ID.ont","ID.mock","ReadLength","FragLength","ReadPID")
  IDvec = rep("",nr);   Strand=rep(-9,nr)  
  ReadLen = rep(0,nr);  FragLen = rep(0,nr);   PID = rep(0.0,nr)
  for (jr in 1:nr){
    for (jc in 2:5){
      t1 = unlist(strsplit(T[jr,cname[jc]],split=splitChar[jc]))
      if (length(t1)>1){
        if (jc==2){
          cstrand = substr(t1[2],start=1,stop=1)
          Strand[jr] = ifelse(cstrand=="+",1,-1)
        } else {
          t11 = t1[2]
          if (jc==3){
            ReadLen[jr] = as.integer(t11)
          } else if (jc==4){
            FragLen[jr] = as.integer(t11)
          } else {
            PID[jr] = as.numeric(as.numeric(substr(t11,start=1,stop=nchar(t11)-1)))
          }
        }
      } else {
        cat("Improper split character for operon",opnum," row",jr, " column",jc,"\n")
        cat("   T[jr,cname[jc]]:  ",T[jr,cname[jc]]," split character:  ",splitChar[jc],"\n")
      }
    }
  }
  T.df = data.frame(ID=T[1:nr,1], strand=Strand, readLength=ReadLen, fragLength=FragLen,PID=PID)
  ifilt1 = which(sapply(1:length(T.df$PID),function(j){T.df$PID[j]>98.75}))  
  cat("Number of retained reads after initial filtering (PID=98.75) is ",length(ifilt1),"\n")
  if (makeplot1){
    plotname1 = paste(stem,"_histos_PID_Qmean_Op_",opnum,".pdf",sep="")
    pdf(file=file.path(basepath,BRoutput,"plots",plotname1),paper="a4")
    par(mfrow=c(2,2))
    hist(T.df[,"PID"],xlab="PID",main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" ") )
    hist(log10(100.001-T.df[,"PID"]),xlab="log10(100.001 - PID)",
         main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" ")) #   which(T.df$PID<98.75)
    breaks1 = 100 - seq(98.74,100,by = 0.02)
    hist(1-T.df[ifilt1,"PID"]/100,breaks=breaks1/100,
         xlab="Fraction Identical",main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" "))
    hist(log10(1.00001-T.df[ifilt1,"PID"]/100),
         xlab="log10(1.00001 - PID/100) (= log10(mismatch rate))",main=paste("Badread-simulated mock10 Op",opnum," PID",sep=" "))
    dev.off()
  }
  outname1 = paste(stem,"_metadata_Pidfilt_Op_",opnum,".RData",sep="")
  save(T.df,ifilt1,file=file.path(basepath,BRoutput,"RData",outname1))
  out = list(Tdf = T.df, PIDfilt=ifilt1)
}


which_specR = function(specName){
  out=which(sapply(1:length(specR),function(j){specR[[j]]$species.ordered==specName}))
}

linKBtospecR = function(){
  # Creates key objects and mappings for 
  #    1. Identifying which KB strains have entries in specR;
  #    2. Ordering KB strains by relative abundance;
  #    3. Mapping abundance-ordered KB strains to their corresponding specR entries.
  #    4. Determining strain operons for any KB strain in specR.
  # 11 August 2025  
  outname = "translate_KB_to_GROND_strains.RData"
  load(file=file.path(grondPath,"output/RData",outname))
  igood = which(ind.specR$KB.index1>0)
#  print(ind.specR$Name[igood])
  inname = "specR_etal_grondDB.RData"
  load(file.path(grondPath,"output/RData",inname))
  
  constructing=FALSE
  if (constructing){
    # Load King's Gut Feeling Knowledge Base.
    grondPath = "/vast/projects/rrn/GROND"
    gfkb.name = "KGFDB.xlsx"  #  "King CH etal SuppMat S4 Table GutFeeling.KB PLoSOne.0206484.s008.xlsx"
    KB = read_excel(file.path(grondPath,"output/text",gfkb.name))
    # Build the mapping from KB to specR
    KBspecR = matrix(0,nrow=164,ncol=3)
    colnames(KBspecR) = c("ind.specR","opLow","opHi")
    # Manually repeat the following for j =1:164, saving the work after each value of j.
    outnameK = "KBspecR_matrix.RData"
    # load(file.path(grondPath,"output/RData",outnameK))
    j=22
    print(KB[j,c(3,8)])
    iz = which_specR("Escherichia coli")
    print(specR[[iz]]$strainOps)
    # KBspecR[j,] = c(0,-1,-1)
    KBspecR[j,] = c(iz,1,2)
    save(KBspecR,file=file.path(grondPath,"output/RData",outnameK))
  }     #     end     conditional   constructing    block
  
  innameK = "KBspecR_matrix.RData"
  load(file.path(grondPath,"output/RData",innameK))
  kbgood = which(KBspecR[,"opHi"]>0);  nkbgd = length(kbgood)
  for (j in 1:nkbgd){print(specR[[KBspecR[kbgood[j],1]]]$strainOps[KBspecR[kbgood[j],2]:KBspecR[kbgood[j],3]])}
  
  # Get KB and KB abundance data to guide rank-ordering on KB abundance data of the strains being used 
  # in mock microbiomes.
  grondPath = "/vast/projects/rrn/GROND"
  gfkb.name = "KGFDB.xlsx"  #  "King CH etal SuppMat S4 Table GutFeeling.KB PLoSOne.0206484.s008.xlsx"
  KB = read_excel(file.path(grondPath,"output/text",gfkb.name))
  
  abundKB.name = "KGFDB_Abundance_Tables.xlsx"
  AbundKB = read_excel(file.path(grondPath,"output/text",abundKB.name))
  ord.abKB = order(AbundKB$Average,decreasing=TRUE)
  # Relation between KB and AbundKB is derived with the following:-
  # Define jord.abund as an index on kbgood such that KB[kbgood[jord.abund]],] gives
  # the KB rows that have strains ordered in descending relative abundances.
  jord.abund = matrix(0,nrow=nkbgd,ncol=2)
  jord.abund[1,] = c(32,2);    jord.abund[2,] = c(13,8);    jord.abund[3,] = c(33,13)
  jord.abund[4,] = c(21,14);   jord.abund[5,] = c(51,20);   jord.abund[6,] = c(57,21)
  jord.abund[7,] = c(64,24);   jord.abund[8,] = c(23,26);   jord.abund[9,] = c(9,37)
  jord.abund[10,] = c(53,33);  jord.abund[11,] = c(70,42);  jord.abund[12,] = c(46,42)
  jord.abund[13,] = c(27,48);  jord.abund[14,] = c(84,49);  jord.abund[15,] = c(66,59)
  jord.abund[16,] = c(34,60);  jord.abund[17,] = c(65,61);  jord.abund[18,] = c(24,62)
  jord.abund[19,] = c(56,63);  jord.abund[20,] = c(11,64);  jord.abund[21,] = c(46,65)
  jord.abund[22,] = c(72,67);  jord.abund[23,] = c(59,68);  jord.abund[24,] = c(54,70)
  jord.abund[25,] = c(87,72);  jord.abund[26,] = c(29,73);  jord.abund[27,] = c(58,74)
  jord.abund[28,] = c(35,75);  jord.abund[29,] = c(71,78);  jord.abund[30,] = c(25,79)
  jord.abund[31,] = c(10,80);  jord.abund[32,] = c(17,81);  jord.abund[33,] = c(38,84)   # not quite(31)?
  jord.abund[34,] = c(49,95);  jord.abund[35,] = c(61,98);  jord.abund[36,] = c(78,99)
  jord.abund[37,] = c(45,100); jord.abund[38,] = c(67,106); jord.abund[39,] = c(85,108)
  jord.abund[40,] = c(44,110); jord.abund[41,] = c(80,111); jord.abund[42,] = c(15,113)
  jord.abund[43,] = c(74,115); jord.abund[44,] = c(26,116); jord.abund[45,] = c(30,119)
  jord.abund[46,] = c(63,120); jord.abund[47,] = c(31,121); jord.abund[48,] = c(79,125)
  jord.abund[49,] = c(7,127);  jord.abund[50,] = c(50,129); jord.abund[51,] = c(28,130)    # not quite (49)?
  jord.abund[52,] = c(55,135); jord.abund[53,] = c(83,137); jord.abund[54,] = c(69,139)
  jord.abund[55,] = c(76,144); jord.abund[56,] = c(82,148); jord.abund[57,] = c(88,149)
  jord.abund[58,] = c(62,150); jord.abund[59,] = c(22,155)
  
  ## For the kth most abundant strain in KB that has strain data in specR here are the
  ## strain operon names:-
  #k = 5;    specRinds3 =  KBspecR[kbgood[jord.abund[k,1]],]
  #specR[[specRinds3[1]]]$strainOps[specRinds3[2]:specRinds3[3]]
  ## and here is the full specR detail:-
  #print(specR[[specRinds3[1]]])
  ra1 = AbundKB[ord.abKB[jord.abund[,2]],16]$Average
  RAkbg = ra1/sum(ra1)
  
  #print(cbind(KB[kbgood[jord.abund[,1]],8], AbundKB[ord.abKB[jord.abund[,2]],c(3,16)]))
  out = list(kbgood,ord.abKB,jord.abund,KB,specR,RAkbg)
}
######################################################################################
############################     RUN INITIALISATION      ##############################
#######################################################################################
whichMock = "mockKB"      #    "mock50"        #   "mock10"
whichSubunit = "23S"
whichCase = "01"
subSampleFactor = 0.4
BRoutput = ifelse(whichMock=="mock10","outputBR10","outputBR50")
fastqPath = file.path(basepath,BRoutput,"fastq",whichSubunit)
grondPath = "/vast/projects/rrn/GROND"
makeplot1 = FALSE  # Covering plotting in PID filtering function
makeplot2 = FALSE  # Covering plotting in Qmean computation function


#######################################################################################
#######################################################################################
##########################                               ##############################
##########################           MAIN BODY           ##############################
##########################                               ##############################
#######################################################################################
#######################################################################################
# PART 1: Specify the mock microbiome, and generate the fasta files of each operon in that
#         mock microbiome.
# Start with GFKB strain names of strains being used. These are manually revised based
# on specR operon names thta have been trimmed to accord with blastn database requirements.
if (whichMock=="mock10"){
  nmock = 10
  # Now load specR to make available the operon data for the various strains of each species.
  outname = "translate_KB_to_GROND_strains.RData"
  load(file=file.path(grondPath,outname))
  igood = which(ind.specR$KB.index1>0)
  print(ind.specR$Name[igood])
  grondPath = "/vast/projects/rrn/GROND"
  inname = "specR_etal_grondDB.RData"
  load(file.path(grondPath,"output/RData",inname))
  # For mock10 the strainNames are (trimmed 24 July 2025):-
  strainNames = c("Phocaeicola vulgatus ATCC 8482","Bacteroides thetaiotaomicron VPI-5482",
                  "Bacteroides fragilis YCH46","Odoribacter splanchnicus DSM 20712",
                  "Bacteroides fragilis NCTC 9343","Escherichia coli CFT073",
                  "Bifidobacterium adolescentis ATCC 15703","Methanobrevibacter smithii ATCC 35061",
                  "Bifidobacterium thermophilum RBL67","Bifidobacterium breve JCM 7019")
  num_ops_per_species = c(7,5,6,4,6,7,5,2,4,2)
  nmock = length(num_ops_per_species)
  indOp = matrix(c(c(1,1+cumsum(num_ops_per_species[1:(nmock-1)])),cumsum(num_ops_per_species)),nrow=nmock,ncol=2)
  # Noting that species 6, E.coli, has actually got 2 strains included (by error) a manual
  # adjustment was made.
  ind.strainOps = c(1,1,13,1,19,591,1,1,1)
} else if (whichMock=="mock50"){
  nmock = 50
  # Now load specR to make available the operon data for the various strains of each species.
  # Now load specR to make available the operon data for the various strains of each species.
  outname = "translate_KB_to_GROND_strains.RData"
  load(file=file.path(grondPath,outname))
  igood = which(ind.specR$KB.index1>0)
  print(ind.specR$Name[igood])
  grondPath = "/vast/projects/rrn/GROND"
  inname = "specR_etal_grondDB.RData"
  load(file.path(grondPath,"output/RData",inname))

    # KB mapping to AbundKB[ord.abKB] - manual on names
  ord.KB = c(83,78,50,158,46,101,110,72,86,124,32,43,60,56,40,99,125,104,89,151,
             48,37,47,131,27,55,73,107,26,129,66,120,132,116,77,76,54,139,149,15,
             12,145,155,162,13,29,14,30,159,31,91,90,51,1,156,41,113,118,100,65,
             67,123,157,8,7,21,22,24,52,63,144,44,62,81,105,102,3,117,135,87,
             98,69,133,96,114,111,163,126,75,88,154,137,138,4,33,2,49,84,109,142,
             71,42,148,160,45,106,164,57,153,108,127,103,152,11,61,18,130,59,39,74, 
             122,36,134,79,16,20,82,92,115,119,112,95,28,97,147,19,150,140,141,38,
             121,58,143,136,53,146,161,5,6,25,128,34,35,68,93,94,64)
  # The following provides a check of consistency.
  zz = cbind(KB[ord.KB[ord.abKB],c("GenBankAC","GenBank name")],AbundKB[ord.abKB,c("accession","taxonomy","Name","Average")])
  # To view the full comparison the screen needs to be widened and the max.print options increase - see below.
  options(max.print = 100000)
  print(zz)
  
  
  # Extract genera and species (exactly 2 strings) for each KB$RPG Name entry
  # Important note - species ordering in AbundKB is alphabetic on genus 
  # then species, but KB is ordered based on 'RPG taxID'.
  # Abundance ordering highest to lowest is oachieved with ord.abKB, below.
  nKB = length(KB$'RPG name')
  
  
  strainNames = ind.specR$Name[igood[1:min(nmock,length(igood))]]
  strainNames[1] = specR[[ind.specR[igood[1],"specR.index2"]]]$strainOps[1]
  strainNames[2] = specR[[ind.specR[igood[2],"specR.index2"]]]$strainOps[1]
  strainNames[3] = specR[[ind.specR[igood[3],"specR.index2"]]]$strainOps[1]
  strainNames[4] = specR[[ind.specR[igood[4],"specR.index2"]]]$strainOps[7]
  strainNames[5] = specR[[ind.specR[igood[5],"specR.index2"]]]$strainOps[1]
  strainNames[6] = specR[[ind.specR[igood[6],"specR.index2"]]]$strainOps[1]
  strainNames[7] = specR[[ind.specR[igood[7],"specR.index2"]]]$strainOps[1]
  strainNames[8] = specR[[ind.specR[igood[8],"specR.index2"]]]$strainOps[1]
  strainNames[9] = specR[[ind.specR[igood[9],"specR.index2"]]]$strainOps[1]
  strainNames[10] = specR[[ind.specR[igood[10],"specR.index2"]]]$strainOps[279]   # Not exact match KB name UMN026/ExPEC; specR name UMNK88
  strainNames[11] = specR[[ind.specR[igood[11],"specR.index2"]]]$strainOps[1]
  strainNames[12] = specR[[ind.specR[igood[12],"specR.index2"]]]$strainOps[1]
  strainNames[13] = specR[[ind.specR[igood[13],"specR.index2"]]]$strainOps[32]
  strainNames[14] = specR[[ind.specR[igood[14],"specR.index2"]]]$strainOps[537]
  strainNames[15] = specR[[ind.specR[igood[15],"specR.index2"]]]$strainOps[4]     # KB strain not specified. 4 strains in specR
  strainNames[16] = specR[[ind.specR[igood[16],"specR.index2"]]]$strainOps[1]
  strainNames[17] = specR[[ind.specR[igood[17],"specR.index2"]]]$strainOps[4]
  strainNames[18] = specR[[ind.specR[igood[18],"specR.index2"]]]$strainOps[474]
  strainNames[19] = specR[[ind.specR[igood[19],"specR.index2"]]]$strainOps[1]
  strainNames[20] = specR[[ind.specR[igood[20],"specR.index2"]]]$strainOps[1]
  strainNames[21] = specR[[ind.specR[igood[21],"specR.index2"]]]$strainOps[28]
  strainNames[22] = specR[[ind.specR[igood[22],"specR.index2"]]]$strainOps[1]
  strainNames[23] = specR[[ind.specR[igood[23],"specR.index2"]]]$strainOps[1]
  strainNames[24] = specR[[ind.specR[igood[24],"specR.index2"]]]$strainOps[250]
  strainNames[25] = specR[[ind.specR[igood[25],"specR.index2"]]]$strainOps[969]
  strainNames[26] = specR[[ind.specR[igood[26],"specR.index2"]]]$strainOps[9]
  strainNames[27] = specR[[ind.specR[igood[27],"specR.index2"]]]$strainOps[1]    # Not exact match; KB name ATCC 43037/JCM 10827/ FDC 338; 3 other strains in specR[[1333]]
  strainNames[28] = specR[[ind.specR[igood[28],"specR.index2"]]]$strainOps[1]
  strainNames[29] = specR[[ind.specR[igood[29],"specR.index2"]]]$strainOps[1]    # KB strain not specified.  3 strains in specR all with 6 operons.
  strainNames[30] = specR[[ind.specR[igood[30],"specR.index2"]]]$strainOps[38]
  strainNames[31] = specR[[ind.specR[igood[51],"specR.index2"]]]$strainOps[1]    # No species in specR matching the KB species/strain for igood[31] so swapped to igood[51]
  strainNames[32] = specR[[ind.specR[igood[32],"specR.index2"]]]$strainOps[1]
  strainNames[33] = specR[[ind.specR[igood[33],"specR.index2"]]]$strainOps[16]   # treat as B.longum subsp. infantis strain 157F
  strainNames[34] = specR[[ind.specR[igood[34],"specR.index2"]]]$strainOps[1]
  strainNames[35] = specR[[ind.specR[igood[35],"specR.index2"]]]$strainOps[1]    # KB strain not specified
  strainNames[36] = specR[[ind.specR[igood[36],"specR.index2"]]]$strainOps[21]
  strainNames[37] = specR[[ind.specR[igood[37],"specR.index2"]]]$strainOps[1]    # KB strain not specified
  strainNames[38] = specR[[ind.specR[igood[38],"specR.index2"]]]$strainOps[1]    # KB strain not specified
  strainNames[39] = specR[[ind.specR[igood[39],"specR.index2"]]]$strainOps[7]
  strainNames[40] = specR[[ind.specR[igood[40],"specR.index2"]]]$strainOps[1]    # KB strain not specified
  strainNames[41] = specR[[ind.specR[igood[41],"specR.index2"]]]$strainOps[1]
  strainNames[42] = specR[[ind.specR[igood[42],"specR.index2"]]]$strainOps[34]
  strainNames[43] = specR[[ind.specR[igood[43],"specR.index2"]]]$strainOps[1]
  strainNames[44] = specR[[ind.specR[igood[44],"specR.index2"]]]$strainOps[20] 
  strainNames[45] = specR[[ind.specR[igood[45],"specR.index2"]]]$strainOps[1] 
  strainNames[46] = specR[[ind.specR[igood[46],"specR.index2"]]]$strainOps[1]    # Klebsiella aerogenes; 2 specR strains, choose first
  strainNames[47] = specR[[ind.specR[igood[47],"specR.index2"]]]$strainOps[1]    # KB strain in Refseq but not specR (should be in GROND) - using representative sequence 
  strainNames[48] = specR[[ind.specR[igood[48],"specR.index2"]]]$strainOps[9]    # Klebsiella aerogenes; 2 specR strains, choose second 
  strainNames[49] = specR[[ind.specR[igood[49],"specR.index2"]]]$strainOps[1] 
  strainNames[50] = specR[[ind.specR[igood[50],"specR.index2"]]]$strainOps[1]
  # Remove the trailing operon number from all these names and change the name of the 
  # vector.
  designStrainNames = sapply(1:nmock,function(j){
    t1 = unlist(strsplit(strainNames[j],split=" ")); nt1=length(t1)
    out = paste(t1[1:(nt1-1)],sep=" ",collapse=" ")})
  
  designSpeciesNames = sapply(1:nmock,function(j){specR[[ind.specR[igood[j],"specR.index2"]]]$species.ordered})
  designSpeciesNames[31] = specR[[ind.specR[igood[31],"specR.index2"]]]$species.ordered
  uniqDesignSpeciesNames = unique(designSpeciesNames);  nuniqDesignSpeciesNames = length(uniqDesignSpeciesNames)
  indRefSpeciesList = lapply(1:nuniqDesignSpeciesNames,function(j){
    vec=which(designSpeciesNames==uniqDesignSpeciesNames[j])
    out=list(species=uniqDesignSpeciesNames[j],index=vec)})
  indRefSpecies = sapply(1:nuniqDesignSpeciesNames,function(j){indRefSpeciesList[[j]]$index})
  nuniqRefSpecies = length(indRefSpecies)
  
  num_ops_per_species = rep(0,nmock)
  ind.strainOps = c(rep(1,3),7,rep(1,5),279,rep(1,2),32,537,4,1,4,474,rep(1,2),28,rep(1,2),
                    250,969,9,rep(1,3),38,rep(1,2),16,rep(1,2),21,rep(1,2),7,rep(1,2),34,1,20,rep(1,3),9,rep(1,2))
  
  for (j in 1:nmock){
    i1 = ind.strainOps[j]
    if (i1>0){
      thisStrain = specR[[ind.specR[igood[j],"specR.index2"]]]$strainOps[i1]
      iub = min(i1+20,length(specR[[ind.specR[igood[j],"specR.index2"]]]$strainOps))
      t1 = unlist(strsplit(thisStrain,split=" "));
      thisStr = paste(t1[1:(length(t1)-1)],sep=" ",collapse=" ")
      im = which(sapply(i1:iub,function(k){
        t1=unlist(strsplit(specR[[ind.specR[igood[j],"specR.index2"]]]$strainOps[k],split=" "))
        check = paste(t1[1:(length(t1)-1)],sep=" ",collapse=" ")  == thisStr}))
      cat("Species ",thisStr,"   im ",im,"\n")
      num_ops_per_species[j] = length(im)
    }
  }
  
  indOp = matrix(c(c(1,1+cumsum(num_ops_per_species[1:(nmock-1)])),cumsum(num_ops_per_species)),nrow=nmock,ncol=2)
}

speciesNames = sapply(1:nmock,function(j){
                       t1 = unlist(strsplit(strainNames[j],split=" "))
                       out=paste(t1[1:2],sep=" ",collapse=" ")})
# Determine indices into specR of the speciesNames.
iSpec = sapply(1:nmock,function(j){which(sapply(1:length(specR),function(k){specR[[k]]$species.ordered}) == speciesNames[j])})
# Manually inspect the strainNames above and amend to align with those in specR.
# When complete, determine the index set for each strain within strainOps of the relevant specR element.
opIndex = vector("list",nmock)
for (j in 1:nmock){
  specStrains = sapply(1:length(specR[[iSpec[[j]]]]$strainOps),function(k){
                                 t1 = unlist(strsplit(specR[[iSpec[[j]]]]$strainOps[k],split=" "))
                                 out = paste(t1[1:(length(t1)-1)],sep=" ",collapse=" ")})
  s1 = unlist(strsplit(strainNames[j],split = " "))
  strainname = paste(s1[1:(length(s1)-ifelse(whichMock=="mock10",0,1))],sep=" ",collapse=" ")
  opIndex[[j]] = which(specStrains == strainname)
}
# 14 operons are given for E.coli CFT073, which is clearly wrong.  We take the first 7 of these.
if (whichMock=="mock10"){
  opIndex[[6]] = opIndex[[6]][1:7]
}
nOpsMock = sum(sapply(1:nmock,function(j){length(opIndex[[j]])}))
# Need to index from specR ops to GROND strain DB indexing.
jcount = 1
opSpecDBindex = matrix(0,nrow=length(specR),ncol=2)
for (j in 1:length(specR)){
  opSpecDBindex[j,1] = jcount
  nops = length(specR[[j]]$strainOps)
  jcount = jcount+nops
  opSpecDBindex[j,2] = jcount-1
}
# Now select the fasta sequences from the relevant multifasta<rRNAgene> sub-directory and write
# to outPath (= /vast/projects/rrn/nanoporeSimulation/mock/mock50/input,  for instance).
# Also write as text the sequence lengths of all the fasta files written.
inPath = file.path(basepath,paste("multifasta",whichSubunit,sep=""))
instem = paste("grondRefseq_",whichSubunit,"_op",sep="")
outPath = file.path(basepath,"mock",whichMock,"input")
opcount = 0
outstem = paste(whichMock,whichSubunit,"_Op_",sep="")
fastaseqLengths = rep(0,10*nmock)
for (jsp in 1:nmock){
  jopSet = opSpecDBindex[iSpec[jsp],1]-1+opIndex[[jsp]]
  for (jjop in 1:length(jopSet)){
    jop = jopSet[jjop]
    opcount = opcount + 1
    cat("Species ",jsp," strainDB op index ",jop,"  outname ",paste(outstem,opcount,".fasta",sep=""),"\n")
    f1 = readFasta(dirPath=inPath,pattern=paste(whichSubunit,"_op",jop,sep="",collapse=""))
    # Modify ShortRead object's id to have no spaces, using "_" instead. Needed to ensure badread-generated
    # fastq objects have full mock strain operon name in header.
    newid = newid = paste(unlist(strsplit(as.character(ShortRead::id(f1[1])),split=" ")),sep="_",collapse="_")
    newf1 = ShortRead(sread(f1[1]),id = BStringSet(newid))
    f1 = newf1
    if (width(f1) >5600) cat("\n Case jsp = ",jsp,"    jop = ",jop,"  too long.\n")
    writeFasta(f1,file=file.path(outPath,whichSubunit,paste(outstem,opcount,".fasta",sep="")))
    fastaseqLengths[opcount] = width(f1)
  }
}
fastaseqLengths = fastaseqLengths[1:opcount]
seqLenName = paste("frag",whichSubunit,"length.sh",sep="")
line1 = paste("lengths=(",paste(fastaseqLengths,sep=" ",collapse=" "),")",sep="")
writeLines(line1,con=file.path(basepath,"mock",whichMock,"output/text",seqLenName))

# PART 2:  Can only be run after generation of simulated reads has completed, as this
#          gives us the fastq records for each read of each operon.
# Determine the maximum number of sequences for the most abundant species.  This requires
# determination of the minimum number of simulated sequences for the various operons of 
# this species.
# It is possible to filter on strandedness, so this will be implemented as an option.
tic()
extractFastqHeaders(fastqPath,file.path(basepath,BRoutput),maxopnum)
toc()

# Now carry out quality filtering using the header information on read PID values.
#  - code transferred from outBadread_filter_analysis.R
cat("fastqPath is:   ",fastqPath,"\n","Subunit is  ",whichSubunit,"\n")
tic()
PIDFilts = mclapply(1:maxopnum,BRfastq_filtPID,fastqPath,whichSubunit,BRoutput,makeplot1,mc.cores=numcores)
toc()
cat("Completed filtering calculation. \n")


stem = paste(whichMock,whichSubunit,"Case",whichCase,sep="_")

minFastqSeq = 10000000
iPIDfilt = vector("list",nmock)
for (jop in 1:num_ops_per_species[1]){
  inname = paste("reads_",whichSubunit,"_Op_",jop,"_metadata_Pidfilt_Op_",jop,".RData",sep="")
  load(file.path(basepath,BRoutput,"RData",inname))
  iPIDfilt[[jop]] = ifilt1
  ipostr= which(T.df$strand[ifilt1]>0);  inegstr = which(T.df$strand[ifilt1]<0)
  minFastqSeq = min(minFastqSeq,length(ipostr))
  print(c(length(ipostr),minFastqSeq))
}

if (whichMock=="mock50"){
  # Select a value of M to define the range of relative abundances from 1 to M - e.g. M=1000
  M = 1000
  RA = generate_RA(nmock,M)
} else {
  # From King etal's GFDB the relative abundances for the selected species are
  abund.Z = c(0.15, 0.0378, 0.0218, 0.0112, 0.00491,0.00259, 0.00185, 0.000705, 0.000046, 0.000042)
  RA = abund.Z/sum(abund.Z)
}
totReads = round(subSampleFactor*minFastqSeq/RA[1]  - 1)
numReads_per_operon_of_species = (totReads*RA)%/%1
Ntotreads = sum(sapply(1:nmock,function(j){numReads_per_operon_of_species[j]*num_ops_per_species[j]}))
cat("Number of reads per operon of each strain is \n",numReads_per_operon_of_species,"\n")
cat("Number of reads in this dataset is ",Ntotreads,"\n")


# Select the fastq records that are to be retained for each operon, and write to
# file.
tic()
qmode="w"
mockFastqName = paste(stem,".fastq",sep="")
for (jsp in 1:nmock){
  nR = numReads_per_operon_of_species[jsp]
  for (jop in indOp[jsp,1]:indOp[jsp,2]){
    inname = paste("reads_",whichSubunit,"_Op_",jop,"_metadata_Pidfilt_Op_",jop,".RData",sep="")
    load(file.path(basepath,BRoutput,"RData",inname))
    ipostr= which(T.df$strand[ifilt1]>0);  inegstr = which(T.df$strand[ifilt1]<0)
    isamp = sample(1:length(ipostr),nR)
    iPIDfilt[[jop]] = ifilt1
    fastqname = paste(stem,jop,".fastq",sep="")
    pat = paste("Op_",jop,".fastq",sep="")
    F = readFastq(dirPath = fastqPath, pattern=pat)
    writeFastq(F[ipostr[isamp]],file.path(basepath,"input/fastq",mockFastqName),mode=qmode, compress=FALSE)
    qmode = "a"
  }
}
toc()







